"""Generated for every run from the automation principal's scope: never part of the project.

Each database of the team's environment becomes a catalog named after its display name
(`-` becomes `_`), so projects stay the same across development, acceptance and production.
"""

from .errors import DbtError

PROFILE = "iceberg_platform"
# Generated for every run; a copy in the project is ignored.
RESERVED_FILES = {"profiles.yml", "catalogs.yml"}
SECRET = "polaris"


def alias(name):
    return name.replace("-", "_")


def catalogs(scope, catalog_uri):
    databases = {}
    for database in scope["databases"]:
        key = alias(database["name"])
        if key in databases:
            raise DbtError(409, f"Two databases map to the catalog name {key}. Rename one of them.", "catalog_clash")
        databases[key] = database
    lines = ["# Generated by the dbt stack for this run. Do not commit.", "catalogs:"]
    for key, database in sorted(databases.items()):
        lines += [
            f"  - name: {key}",
            "    type: iceberg_rest",
            "    table_format: iceberg",
            "    config:",
            "      duckdb:",
            f"        endpoint: {catalog_uri}",
            f"        warehouse: {database['id']}",
            f"        secret: {SECRET}",
            "        access_delegation_mode: vended_credentials",
            "        support_nested_namespaces: true",
            f"        catalog_database: {key}",
        ]
    return "\n".join(lines) + "\n", {key: d["id"] for key, d in databases.items()}


def profiles(environment, threads=4):
    return "\n".join([
        "# Generated by the dbt stack for this run.",
        f"{PROFILE}:",
        f"  target: {environment}",
        "  outputs:",
        f"    {environment}:",
        "      type: duckdb",
        '      path: ":memory:"',
        "      schema: main",
        f"      threads: {threads}",
        "      secrets:",
        f"        - name: {SECRET}",
        "          type: iceberg",
        "          token: \"{{ env_var('DBT_ENV_SECRET_POLARIS_TOKEN') }}\"",
    ]) + "\n"
