"""Create this stack's .env next to the handshake file the platform wrote (.env.bridge)."""

import os
import secrets
from pathlib import Path
from urllib.parse import urlsplit

ROOT = Path(__file__).resolve().parent.parent


def read(path):
    values = {}
    for line in path.read_text().splitlines():
        key, sep, value = line.partition("=")
        if sep and not key.startswith("#"):
            values[key.strip()] = value.strip()
    return values


def setup(root=ROOT):
    bridge = root / ".env.bridge"
    if not bridge.exists():
        raise SystemExit(
            "No .env.bridge. Register the stack with the platform first, from the platform directory:\n"
            "  uv run python -m scripts.setup --extension dbt --origin http://localhost:3004 "
            "--handshake stacks/dbt/.env.bridge")
    handshake = read(bridge)
    if handshake.get("BRIDGE_CONTRACT") != "1":
        raise SystemExit("This dbt stack needs a Bridge v1 handshake file.")
    config = root / ".env"
    values = read(config) if config.exists() else {}
    origin = urlsplit(handshake["EXTENSION_ORIGIN"])
    values.setdefault("LAUNCHER_TOKEN", secrets.token_hex(24))
    values["PLATFORM_NETWORK"] = handshake["PLATFORM_NETWORK"]
    values["DBT_PORT"] = str(origin.port or (443 if origin.scheme == "https" else 80))
    content = "".join(f"{k}={v}\n" for k, v in values.items())
    if config.exists():
        config.unlink()
    with os.fdopen(os.open(config, os.O_CREAT | os.O_EXCL | os.O_WRONLY, 0o600), "w") as file:
        file.write("# Generated by scripts.setup; the bridge credentials stay in .env.bridge.\n" + content)
    print("Ready. Build and start the stack:\n"
          "  docker compose --profile images build && docker compose up -d --wait")


if __name__ == "__main__":
    setup()
