"""Generate configuration for a new local Keycloak installation."""

import argparse
import json
import os
import re
import secrets
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def mapper(name, kind, config):
    return {"name": name, "protocol": "openid-connect", "protocolMapper": kind, "config": config}


def realm(env):
    clients = []
    for name, origin, secret in [("iceberg-admin", env["PORTAL_ORIGIN"], "PORTAL"),
                                 ("iceberg-users", env["USER_ORIGIN"], "USERS")]:
        mappers = [mapper("polaris-audience", "oidc-audience-mapper", {
            "included.custom.audience": "polaris", "access.token.claim": "true", "id.token.claim": "false",
        })]
        for attribute, claim, kind in [("polaris_id", "principal_id", "long"),
                                       ("polaris_name", "principal_name", "String")]:
            mappers.append(mapper(attribute, "oidc-usermodel-attribute-mapper", {
                "user.attribute": attribute, "claim.name": "polaris." + claim,
                "jsonType.label": kind, "access.token.claim": "true", "id.token.claim": "false",
            }))
        mappers.append(mapper("polaris-roles", "oidc-hardcoded-claim-mapper", {
            "claim.name": "polaris.roles", "claim.value": '["PRINCIPAL_ROLE:ALL"]',
            "jsonType.label": "JSON", "access.token.claim": "true", "id.token.claim": "false",
        }))
        clients.append({
            "clientId": name, "enabled": True, "protocol": "openid-connect", "publicClient": False,
            "secret": "${OIDC_" + secret + "_SECRET}", "standardFlowEnabled": True,
            "directAccessGrantsEnabled": False, "serviceAccountsEnabled": False,
            "redirectUris": [origin + "/auth/callback"],
            "webOrigins": [origin],
            "attributes": {"pkce.code.challenge.method": "S256",
                           "post.logout.redirect.uris": origin + "/"},
            "defaultClientScopes": ["basic", "profile", "roles"], "protocolMappers": mappers,
        })
    users = [{
        "username": env["PLATFORM_ADMIN_USERNAME"], "enabled": True,
        "firstName": "Platform", "lastName": "Administrator",
        "email": "platform-admin@example.test", "emailVerified": True,
        "requiredActions": ["UPDATE_PASSWORD"],
        "credentials": [{"type": "password", "value": "${PLATFORM_ADMIN_PASSWORD}", "temporary": True}],
        "clientRoles": {"iceberg-admin": ["platform-admin"]},
    }]
    return {
        "realm": "iceberg", "enabled": True, "registrationAllowed": False,
        "resetPasswordAllowed": False, "rememberMe": False, "accessTokenLifespan": 900,
        "ssoSessionIdleTimeout": 1800, "ssoSessionMaxLifespan": 28800,
        "roles": {"client": {"iceberg-admin": [{"name": "platform-admin"}]}},
        "clients": clients, "users": users,
    }


def read_env(path):
    # Read literal assignments generated by this tool; do not expand secret values.
    values = {}
    for line in path.read_text().splitlines():
        key, sep, value = line.partition("=")
        if sep and not key.startswith("#"):
            values[key.strip()] = value.strip().strip("\"'")
    return values


def setup(root=ROOT, demo=False):
    config = root / ".env"
    template = (root / ".env.example").read_text()
    content = re.sub(r"replace-with-generated-(password|secret)", lambda _: secrets.token_hex(24), template)
    if not config.exists():
        with os.fdopen(os.open(config, os.O_CREAT | os.O_EXCL | os.O_WRONLY, 0o600), "w") as file:
            file.write(content)
    values = read_env(config)
    additions = {}

    def default(key, value):
        if key not in values:
            additions[key] = values[key] = value

    for key in ("KEYCLOAK_ADMIN_PASSWORD", "OIDC_PORTAL_SECRET", "OIDC_USERS_SECRET",
                "OIDC_MANAGEMENT_SECRET", "PLATFORM_ADMIN_PASSWORD"):
        default(key, secrets.token_hex(24))
    for key, value in {
        "PLATFORM_ADMIN_USERNAME": "platform-admin", "KEYCLOAK_PORT": "8080",
        "PORTAL_ORIGIN": f"http://localhost:{values.get('PORT', '3000')}",
        "USER_ORIGIN": f"http://localhost:{values.get('USER_PORT', '3002')}",
        "KEYCLOAK_ORIGIN": f"http://localhost:{values.get('KEYCLOAK_PORT', '8080')}",
    }.items():
        default(key, value)
    default("OIDC_ISSUER", values["KEYCLOAK_ORIGIN"] + "/realms/iceberg")
    default("OIDC_INTERNAL_ISSUER", values["OIDC_ISSUER"])
    default("KEYCLOAK_IMPORT_FILE", "./.local/keycloak/iceberg-realm.json")
    if demo:
        for account in ("admin", "writer", "reader", "outsider"):
            default(f"DEMO_{account.upper()}_PASSWORD", secrets.token_hex(24))
    if additions:
        with config.open("a") as file:
            file.write("\n# Keycloak identity and access management\n")
            file.writelines(f"{key}={value}\n" for key, value in additions.items())
    config.chmod(0o600)
    target = root / values["KEYCLOAK_IMPORT_FILE"]
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(json.dumps(realm(values), indent=2) + "\n")
    print("Keycloak configuration ready in .env.")
    print("Start compose.yaml (platform), then compose.users.yaml (workspaces).")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--demo", action="store_true", help="Generate credentials for optional test fixtures")
    args = parser.parse_args()
    setup(demo=args.demo)


if __name__ == "__main__":
    main()
elif __name__ == "<run_path>":
    setup()
