import { chromium, expect } from '@playwright/test';
let input = ''; for await (const chunk of process.stdin) input += chunk;
const data = JSON.parse(input);
const browser = await chromium.launch({headless: true, executablePath: process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE || undefined});
let page;
try {
  const context = await browser.newContext({viewport: {width: 1440, height: 1000}});
  await context.addCookies([{name: 'iceberg_user_session', value: data.cookie, url: data.baseURL, httpOnly: true, sameSite: 'Strict'}]);
  page = await context.newPage();
  page.setDefaultTimeout(20000);
  const errors = []; page.on('pageerror', e => errors.push(e.message));
  const sockets = []; page.on('websocket', ws => { const socket = {url: ws.url(), received: 0}; sockets.push(socket); ws.on('framereceived', () => socket.received++); });
  await page.goto(data.baseURL);
  await page.locator('#workspace-screen').waitFor({state: 'visible'});
  await page.getByRole('button', {name: 'Switch to light mode', exact: true}).click();
  await page.reload();
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'light');
  await page.locator('#workspace-screen').waitFor({state: 'visible'});
  await page.locator('#databases button').filter({hasText: data.databaseName}).click();
  await page.getByRole('button', {name: 'Open →', exact: true}).click();
  await page.getByRole('button', {name: 'Open →', exact: true}).click();
  await page.locator('.object-label').filter({hasText: 'events'}).waitFor();
  await page.locator('.object-label').filter({hasText: 'event_report'}).waitFor();
  await page.screenshot({path: 'test-results/users-catalog-light.png', fullPage: true});
  await page.getByRole('button', {name: 'Switch to dark mode', exact: true}).click();
  await expect(page.locator('#open-notebook')).toHaveCSS('background-color', 'rgb(255, 255, 255)');
  await expect(page.locator('#open-notebook')).toHaveCSS('color', 'rgb(0, 0, 0)');
  await page.screenshot({path: 'test-results/users-catalog-dark.png', fullPage: true});
  await page.locator('#notebooks button').first().click();
  const frame = page.frameLocator('#frame-host iframe');
  await frame.locator('.cm-content').first().waitFor();
  await frame.locator('.cm-content').first().click();
  await page.keyboard.press('Control+Shift+r');
  // Both real reactive execution and the WebSocket proxy are required here.
  await frame.getByRole('heading', {name: 'Available objects', exact: true}).waitFor({timeout: 60000});
  await frame.getByText('deploy', {exact: true}).first().waitFor({timeout: 60000});
  const saved = page.waitForResponse(r => r.url().includes('/workspaces/') && r.url().endsWith('/save') && r.request().method() === 'POST');
  await frame.locator('.cm-content').first().click();
  await page.keyboard.press('Control+End');
  await page.keyboard.press('End');
  await page.keyboard.press('Enter');
  await page.keyboard.insertText('# portal-browser-save-proof');
  const saveResponse = await saved;
  if (!saveResponse.ok()) throw new Error('Notebook save failed');
  if (!sockets.some(s => s.url.includes('/workspaces/') && s.received > 0)) throw new Error('No working marimo WebSocket');
  if (errors.length) throw new Error(errors.join('\n'));
  await page.screenshot({path: 'test-results/users-desktop.png', fullPage: true});
  await page.getByRole('button', {name: 'Catalog', exact: true}).click();
  await page.setViewportSize({width: 390, height: 844});
  if (await page.evaluate(() => document.documentElement.scrollWidth > innerWidth)) throw new Error('Mobile page overflows');
  await page.screenshot({path: 'test-results/users-mobile.png', fullPage: true});
  await page.getByRole('button', {name: 'Switch to light mode', exact: true}).click();
  if (await page.evaluate(() => document.documentElement.scrollWidth > innerWidth)) throw new Error('Light mobile page overflows');
  await expect(page.locator('#open-notebook')).toHaveCSS('background-color', 'rgb(0, 0, 0)');
  await expect(page.locator('#open-notebook')).toHaveCSS('color', 'rgb(245, 245, 245)');
  await page.screenshot({path: 'test-results/users-mobile-light.png', fullPage: true});
  console.log('PASS: persistent dark/light themes, browser catalog, marimo WebSocket and table execution, mobile layout');
  await page.locator('#notebooks button').first().click();
  await page.getByRole('combobox', {name: 'Notebook', exact: true}).selectOption({label: 'Shared files'});
  await expect(page.locator('#frame-host iframe')).toHaveAttribute('src', data.notebook.filesUrl);
  await expect(page.getByRole('combobox', {name: 'Environment', exact: true}).locator('option')).toHaveText(['Development', 'Acceptance', 'Production']);
  await page.getByRole('combobox', {name: 'Environment', exact: true}).selectOption('production');
  await expect(page.locator('#databases button')).toHaveCount(1);
  await expect(page.locator('#databases button')).toContainText(data.databaseName);
  await expect(page.locator('#databases button small')).toHaveText('Production');
  await page.getByRole('combobox', {name: 'Environment', exact: true}).selectOption('acceptance');
  await expect(page.locator('#databases button')).toHaveCount(0);
  await expect(page.locator('#databases')).toContainText('no databases in this environment');
  await page.getByRole('combobox', {name: 'Environment', exact: true}).selectOption('development');
  await expect(page.locator('#databases button small')).toHaveText('Development');
  console.log('PASS: shared-file selector and Development / Acceptance / Production navigation');
  await context.close();
} catch (error) { if (page) { await page.screenshot({path: 'test-results/users-failure.png', fullPage: true}); for (const f of page.frames()) console.error((await f.locator('body').innerText()).slice(0, 7000)); } throw error; } finally { await browser.close(); }
